import type { NameOfAllah } from "@/types";

export const NAMES_OF_ALLAH: NameOfAllah[] = [
  { number: 1, name: "الرحمن", transliteration: "Ar-Rahman", meaning: "The Beneficent", meaningAr: "المنعم بجلائل النعم" },
  { number: 2, name: "الرحيم", transliteration: "Ar-Raheem", meaning: "The Merciful", meaningAr: "المنعم بدقائق النعم" },
  { number: 3, name: "الملك", transliteration: "Al-Malik", meaning: "The King", meaningAr: "الظاهر بقهره وقدرته" },
  { number: 4, name: "القدوس", transliteration: "Al-Quddus", meaning: "The Most Holy", meaningAr: "المنزه عن كل نقص" },
  { number: 5, name: "السلام", transliteration: "As-Salam", meaning: "The Source of Peace", meaningAr: "ناشر السلام" },
  { number: 6, name: "المؤمن", transliteration: "Al-Mu'min", meaning: "The Giver of Faith", meaningAr: "مصدق عباده المخلصين" },
  { number: 7, name: "المهيمن", transliteration: "Al-Muhaymin", meaning: "The Guardian", meaningAr: "المسيطر على كل شيء" },
  { number: 8, name: "العزيز", transliteration: "Al-Aziz", meaning: "The Almighty", meaningAr: "القوي الغالب" },
  { number: 9, name: "الجبار", transliteration: "Al-Jabbar", meaning: "The Compeller", meaningAr: "الذي ينفذ مشيئته" },
  { number: 10, name: "المتكبر", transliteration: "Al-Mutakabbir", meaning: "The Tremendous", meaningAr: "المتعالي عن صفات الخلق" },
  { number: 11, name: "الخالق", transliteration: "Al-Khaliq", meaning: "The Creator", meaningAr: "الموجد للأشياء" },
  { number: 12, name: "البارئ", transliteration: "Al-Bari'", meaning: "The Righteous", meaningAr: "الذي خلق الخلق" },
  { number: 13, name: "المصور", transliteration: "Al-Musawwir", meaning: "The Fashioner", meaningAr: "مبدع الصور" },
  { number: 14, name: "الغفار", transliteration: "Al-Ghaffar", meaning: "The Forgiving", meaningAr: "الذي يستر العيوب" },
  { number: 15, name: "القهار", transliteration: "Al-Qahhar", meaning: "The Subduer", meaningAr: "الغالب لكل شيء" },
  { number: 16, name: "الوهاب", transliteration: "Al-Wahhab", meaning: "The Bestower", meaningAr: "كثير العطاء" },
  { number: 17, name: "الرزاق", transliteration: "Ar-Razzaq", meaning: "The Provider", meaningAr: "الذي يرزق العباد" },
  { number: 18, name: "الفتاح", transliteration: "Al-Fattah", meaning: "The Opener", meaningAr: "الذي يفتح أبواب الرحمة" },
  { number: 19, name: "العليم", transliteration: "Al-Alim", meaning: "The All-Knowing", meaningAr: "المحيط بكل شيء" },
  { number: 20, name: "القابض", transliteration: "Al-Qabid", meaning: "The Withholder", meaningAr: "الذي يضيق الرزق" },
  { number: 21, name: "الباسط", transliteration: "Al-Basit", meaning: "The Expander", meaningAr: "الذي يوسع الرزق" },
  { number: 22, name: "الخافض", transliteration: "Al-Khafid", meaning: "The Abaser", meaningAr: "الذي يخفض الكافرين" },
  { number: 23, name: "الرافع", transliteration: "Ar-Rafi", meaning: "The Exalter", meaningAr: "الذي يرفع المؤمنين" },
  { number: 24, name: "المعز", transliteration: "Al-Mu'izz", meaning: "The Bestower of Honor", meaningAr: "الذي يعز من يشاء" },
  { number: 25, name: "المذل", transliteration: "Al-Mudhill", meaning: "The Humiliator", meaningAr: "الذي يذل من يشاء" },
  { number: 26, name: "السميع", transliteration: "As-Sami", meaning: "The All-Hearing", meaningAr: "الذي يسمع كل شيء" },
  { number: 27, name: "البصير", transliteration: "Al-Basir", meaning: "The All-Seeing", meaningAr: "الذي يرى كل شيء" },
  { number: 28, name: "الحكم", transliteration: "Al-Hakam", meaning: "The Judge", meaningAr: "الذي يحكم بين الخلق" },
  { number: 29, name: "العدل", transliteration: "Al-Adl", meaning: "The Just", meaningAr: "المنزه عن الظلم" },
  { number: 30, name: "اللطيف", transliteration: "Al-Latif", meaning: "The Subtle One", meaningAr: "الرفيق بعباده" },
  { number: 31, name: "الخبير", transliteration: "Al-Khabir", meaning: "The All-Aware", meaningAr: "المحيط ببواطن الأمور" },
  { number: 32, name: "الحليم", transliteration: "Al-Halim", meaning: "The Forbearing", meaningAr: "الذي لا يعجل بالعقوبة" },
  { number: 33, name: "العظيم", transliteration: "Al-Azim", meaning: "The Magnificent", meaningAr: "المنزه عن كل نقص" },
  { number: 34, name: "الغفور", transliteration: "Al-Ghafur", meaning: "The Forgiving", meaningAr: "الذي يغفر الذنوب" },
  { number: 35, name: "الشكور", transliteration: "Ash-Shakur", meaning: "The Grateful", meaningAr: "الذي يجزي بالخير" },
  { number: 36, name: "العلي", transliteration: "Al-Ali", meaning: "The Most High", meaningAr: "الذي علا بذاته" },
  { number: 37, name: "الكبير", transliteration: "Al-Kabir", meaning: "The Greatest", meaningAr: "المنزه عن صفات الخلق" },
  { number: 38, name: "الحفيظ", transliteration: "Al-Hafiz", meaning: "The Preserver", meaningAr: "الحافظ لكل شيء" },
  { number: 39, name: "المقيت", transliteration: "Al-Muqit", meaning: "The Maintainer", meaningAr: "الذي يوصل الأقوات" },
  { number: 40, name: "الحسيب", transliteration: "Al-Hasib", meaning: "The Reckoner", meaningAr: "الكافي لعباده" },
  { number: 41, name: "الجليل", transliteration: "Al-Jalil", meaning: "The Sublime One", meaningAr: "الموصوف بصفات الجلال" },
  { number: 42, name: "الكريم", transliteration: "Al-Karim", meaning: "The Generous One", meaningAr: "كثير العطاء" },
  { number: 43, name: "الرقيب", transliteration: "Ar-Raqib", meaning: "The Watchful", meaningAr: "المطلع على العباد" },
  { number: 44, name: "المجيب", transliteration: "Al-Mujib", meaning: "The Responsive", meaningAr: "الذي يجيب الدعاء" },
  { number: 45, name: "الواسع", transliteration: "Al-Wasi", meaning: "The All-Encompassing", meaningAr: "الذي وسع كل شيء" },
  { number: 46, name: "الحكيم", transliteration: "Al-Hakim", meaning: "The Wise", meaningAr: "المصيب في أفعاله" },
  { number: 47, name: "الودود", transliteration: "Al-Wadud", meaning: "The Loving One", meaningAr: "المحب لعباده" },
  { number: 48, name: "المجيد", transliteration: "Al-Majid", meaning: "The Most Glorious One", meaningAr: "الشريف في ذاته" },
  { number: 49, name: "الباعث", transliteration: "Al-Ba'ith", meaning: "The Resurrector", meaningAr: "الذي يبعث الموتى" },
  { number: 50, name: "الشهيد", transliteration: "Ash-Shahid", meaning: "The Witness", meaningAr: "المطلع على كل شيء" },
  { number: 51, name: "الحق", transliteration: "Al-Haqq", meaning: "The Truth", meaningAr: "الثابت بذاته" },
  { number: 52, name: "الوكيل", transliteration: "Al-Wakil", meaning: "The Trustee", meaningAr: "القائم بمصالح العباد" },
  { number: 53, name: "القوي", transliteration: "Al-Qawi", meaning: "The Most Strong", meaningAr: "تام القدرة" },
  { number: 54, name: "المتين", transliteration: "Al-Matin", meaning: "The Firm One", meaningAr: "شديد القوة" },
  { number: 55, name: "الولي", transliteration: "Al-Wali", meaning: "The Protecting Associate", meaningAr: "الناصر للمؤمنين" },
  { number: 56, name: "الحميد", transliteration: "Al-Hamid", meaning: "The Praiseworthy", meaningAr: "المستحق للحمد" },
  { number: 57, name: "المحصي", transliteration: "Al-Muhsi", meaning: "The Counter", meaningAr: "المحيط بكل شيء" },
  { number: 58, name: "المبدئ", transliteration: "Al-Mubdi", meaning: "The Originator", meaningAr: "الذي بدأ الخلق" },
  { number: 59, name: "المعيد", transliteration: "Al-Mu'id", meaning: "The Restorer", meaningAr: "الذي يعيد الخلق" },
  { number: 60, name: "المحيي", transliteration: "Al-Muhyi", meaning: "The Giver of Life", meaningAr: "الذي يحيي الأجسام" },
  { number: 61, name: "المميت", transliteration: "Al-Mumit", meaning: "The Creator of Death", meaningAr: "الذي يميت الأحياء" },
  { number: 62, name: "الحي", transliteration: "Al-Hayy", meaning: "The Ever-Living", meaningAr: "الباقي الذي لا يموت" },
  { number: 63, name: "القيوم", transliteration: "Al-Qayyum", meaning: "The Self-Subsisting", meaningAr: "القائم بنفسه" },
  { number: 64, name: "الواجد", transliteration: "Al-Wajid", meaning: "The Perceiver", meaningAr: "الذي يجد ما يطلب" },
  { number: 65, name: "الماجد", transliteration: "Al-Majid", meaning: "The Illustrious One", meaningAr: "كثير الشرف" },
  { number: 66, name: "الواحد", transliteration: "Al-Wahid", meaning: "The Unique", meaningAr: "المنزه عن التعدد" },
  { number: 67, name: "الأحد", transliteration: "Al-Ahad", meaning: "The One", meaningAr: "الفرد الذي لا يتجزأ" },
  { number: 68, name: "الصمد", transliteration: "As-Samad", meaning: "The Eternal", meaningAr: "المقصود في الحوائج" },
  { number: 69, name: "القادر", transliteration: "Al-Qadir", meaning: "The Able", meaningAr: "المستغني عن المعونة" },
  { number: 70, name: "المقتدر", transliteration: "Al-Muqtadir", meaning: "The Powerful", meaningAr: "المظهر لقدرته" },
  { number: 71, name: "المقدم", transliteration: "Al-Muqaddim", meaning: "The Expediter", meaningAr: "الذي يقدم من يشاء" },
  { number: 72, name: "المؤخر", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer", meaningAr: "الذي يؤخر من يشاء" },
  { number: 73, name: "الأول", transliteration: "Al-Awwal", meaning: "The First", meaningAr: "السابق للأشياء" },
  { number: 74, name: "الآخر", transliteration: "Al-Akhir", meaning: "The Last", meaningAr: "الباقي بعد فناء الخلق" },
  { number: 75, name: "الظاهر", transliteration: "Az-Zahir", meaning: "The Manifest", meaningAr: "الغالب بآياته" },
  { number: 76, name: "الباطن", transliteration: "Al-Batin", meaning: "The Hidden", meaningAr: "المحيط ببواطن الأمور" },
  { number: 77, name: "الوالي", transliteration: "Al-Wali", meaning: "The Governor", meaningAr: "المالك للأشياء" },
  { number: 78, name: "المتعالي", transliteration: "Al-Muta'ali", meaning: "The Most Exalted", meaningAr: "المنزه عن صفات الخلق" },
  { number: 79, name: "البر", transliteration: "Al-Barr", meaning: "The Source of All Goodness", meaningAr: "المحسن لعباده" },
  { number: 80, name: "التواب", transliteration: "At-Tawwab", meaning: "The Acceptor of Repentance", meaningAr: "الذي يقبل التوبة" },
  { number: 81, name: "المنتقم", transliteration: "Al-Muntaqim", meaning: "The Avenger", meaningAr: "المعاقب للعصاة" },
  { number: 82, name: "العفو", transliteration: "Al-Afuww", meaning: "The Pardoner", meaningAr: "الذي يمحو الذنوب" },
  { number: 83, name: "الرؤوف", transliteration: "Ar-Ra'uf", meaning: "The Compassionate", meaningAr: "شديد الرحمة" },
  { number: 84, name: "مالك الملك", transliteration: "Malik-ul-Mulk", meaning: "The Owner of All", meaningAr: "المتصرف في ملكه" },
  { number: 85, name: "ذو الجلال والإكرام", transliteration: "Dhu-l-Jalal wa-l-Ikram", meaning: "The Lord of Majesty and Bounty", meaningAr: "المستحق للتمجيد" },
  { number: 86, name: "المقسط", transliteration: "Al-Muqsit", meaning: "The Equitable", meaningAr: "العادل في حكمه" },
  { number: 87, name: "الجامع", transliteration: "Al-Jami", meaning: "The Gatherer", meaningAr: "الذي يجمع الخلائق" },
  { number: 88, name: "الغني", transliteration: "Al-Ghani", meaning: "The Self-Sufficient", meaningAr: "المستغني عن الخلق" },
  { number: 89, name: "المغني", transliteration: "Al-Mughni", meaning: "The Enricher", meaningAr: "الذي يغني من يشاء" },
  { number: 90, name: "المانع", transliteration: "Al-Mani", meaning: "The Preventer", meaningAr: "الذي يمنع من يشاء" },
  { number: 91, name: "الضار", transliteration: "Ad-Darr", meaning: "The Distressor", meaningAr: "الذي يسلط الضر" },
  { number: 92, name: "النافع", transliteration: "An-Nafi", meaning: "The Propitious", meaningAr: "الذي يوصل النفع" },
  { number: 93, name: "النور", transliteration: "An-Nur", meaning: "The Light", meaningAr: "الذي يهدي بنوره" },
  { number: 94, name: "الهادي", transliteration: "Al-Hadi", meaning: "The Guide", meaningAr: "الذي يهدي عباده" },
  { number: 95, name: "البديع", transliteration: "Al-Badi", meaning: "The Incomparable", meaningAr: "الذي خلق الخلق بلا مثال" },
  { number: 96, name: "الباقي", transliteration: "Al-Baqi", meaning: "The Everlasting", meaningAr: "الدائم بلا انتهاء" },
  { number: 97, name: "الوارث", transliteration: "Al-Warith", meaning: "The Inheritor", meaningAr: "الباقي بعد فناء الخلق" },
  { number: 98, name: "الرشيد", transliteration: "Ar-Rashid", meaning: "The Guide to the Right Path", meaningAr: "الذي يرشد الخلق" },
  { number: 99, name: "الصبور", transliteration: "As-Sabur", meaning: "The Patient", meaningAr: "الذي لا يعجل بالعقوبة" }
];
